export * from './administrador.repository';
export * from './asesor.repository';
export * from './ciudad.repository';
export * from './cliente.repository';
export * from './departamento.repository';
export * from './solicitud.repository';
export * from './tipo-documento.repository';
export * from './tipo-vehiculo.repository';
export * from './vehiculo.repository';
